added output verification for table create script

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -39,10 +39,10 @@ jobs:
         working-directory: /home/vb2007/prod/discordbot
         run: |
           echo "Starting command deployment..."
-          deployment_output=$(npm run deploy 2>&1)
-          echo "$deployment_output"
+          output=$(npm run deploy 2>&1)
+          echo "$output"
 
-          if echo "$deployment_output" | grep -q "Registered .* slash (/) commands at Discord"; then
+          if echo "$output" | grep -q "Registered .* slash (/) commands at Discord"; then
             echo "✅ Command deployment successful"
           else
             echo "❌ Command deployment failed"
@@ -53,7 +53,16 @@ jobs:
       - name: Updating command data
         working-directory: /home/vb2007/prod/discordbot
         run: |
-          npm run create-tables
+          echo "Starting table creation and command data update..."
+          output=$(npm run create-tables 2>&1)
+          echo "$output"
+
+          if echo "$output" | grep -q "All queries are executed & all tables are processed." && echo "$table_output" | grep -q "Command data has been updated successfully."; then
+            echo "✅ Table creation and command data update successful"
+          else
+            echo "❌ Table creation or command data update failed"
+            exit 1
+          fi
           sleep 5
 
       - name: Starting systemd service
